version: 2.1

jobs:
  checkoutAndTest:
    machine: true
    steps:
      - run: pwd
      - run: ls
      - run: git clone https://github.com/XavierSamuelHuppe/3p5-c3-backend.git
      - run: ls
      - run: cd 3p5-c3-backend

workflows:
  build:
    jobs:
      - checkoutAndTest
