version: 2.1

jobs:
  checkoutAndTest:
    machine: true
    steps:
      - run: git clone https://github.com/XavierSamuelHuppe/3p5-c3-backend.git
      - run: git clone https://github.com/XavierSamuelHuppe/3p5-c3-frontend.git
      - run: cd 3p5-c3-frontend
      - run: npm install
      - run: npm run build
      - run: ls

workflows:
  build:
    jobs:
      - checkoutAndTest
