version: 2.1

jobs:
  oneStep:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: cd cours5 && pwd
      - run: cd cours5 && ls

workflows:
  build:
    jobs:
      - oneStep
